language: node_js

node_js:
  - "6"

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database jambuds_test;' -U postgres

script:
  - npm test

env:
  - DATABASE_URL=postgres://postgres@localhost:5432/jambuds_test

cache:
  directories:
    - node_modules

notifications:
  email: false
