language: node_js

node_js:
  - "8"

addons:
  postgresql: "9.4"

  # this is the last version that supports the selenium extension used I guess??
  firefox: "45.0"

  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - psql -c 'create database jambuds_test;' -U postgres
  # enable firefox
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # run webpack
  # - npm run run-client &
  # a little padding time for things to start up
  # - sleep 5

script:
  - cd api && npm test
  # - npm run features

env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=test

    # In addition to these, API keys for feature tests are included in Travis's settings page
    - DATABASE_URL=postgres://postgres@localhost:5432/jambuds_test
    - PORT=3001
    - SERVER_URL=http://localhost:3001
    - DEV_SERVER_PORT=8080
    - STATIC_URL=http://localhost:8080

cache:
  directories:
    - node_modules

notifications:
  email: false
