language: node_js

node_js:
  - "8"

addons:
  # XXX: HEY THIS IS OUT OF DATE
  # see https://github.com/travis-ci/travis-ci/issues/8537 it's a mess
  postgresql: "9.6"

install:
  - cd api
  - npm install
  - cd ../spec
  - npm install
  - cd ..

before_script:
  - psql -c 'create database jambuds_test;' -U postgres
  - cd app
  - npm dev &
  - sleep 10  # padding to start the dev server
  - cd ..

script:
  - cd api
  - npm test
  - cd ../spec
  - npm test

env:
  global:
    - NODE_ENV=test

    # In addition to these, API keys for feature tests are included in Travis's settings page
    - DATABASE_URL=postgres://postgres@localhost:5432/jambuds_test
    - PORT=3001
    - SERVER_URL=http://localhost:3001
    - STATIC_URL=http://localhost:8080
    - API_URL=http://localhost:8080

cache:
  directories:
    - node_modules

notifications:
  email: false
