version: '3'
services:
  redis:
    image: redis:5.0.3-alpine
    env_file: .env
    ports:
      - "6380:6379"
  db:
    image: postgres:11.2-alpine
    env_file: .env
    environment:
      POSTGRES_DB: jambuds
    ports:
      - "5433:5432"
    volumes:
      - "./tmp/db-data:/var/lib/postgresql/data"