version: '3'
services:
  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6380:6379"
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_MULTIPLE_DATABASES: jambuds,jambuds_test,jambuds_kotlin_test
    ports:
      - "5433:5432"
    volumes:
      - ./docker/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - "./tmp/db-data:/var/lib/postgresql/data"