version: '3'
services:
  jambuds-app:
    image: jambuds-app:latest
    depends_on:
      - jambuds-api
    env_file: .env
  jambuds-api:
    image: jambuds-api:latest
    depends_on:
      - db
      - redis
    env_file: .env
  redis:
    image: redis:5.0.3-alpine
    env_file: .env
  db:
    image: postgres:11.2-alpine
    env_file: .env
    environment:
      POSTGRES_DB: jambuds