version: '3'
services:
  jambuds-app:
    ports:
      - "6000:8080"
    restart: always
    volumes:
      - "./secrets:/home/node/secrets"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/home/node/secrets/gcloud_stackdriver_key.json"
  jambuds-api:
    ports:
      - "6001:3000"
    restart: always
    volumes:
      - "./secrets:/home/node/secrets"
    environment:
      MUSICKIT_PRIVATE_KEY_PATH: "/home/node/secrets/jam_buds_prod_key.p8"
      GOOGLE_APPLICATION_CREDENTIALS: "/home/node/secrets/gcloud_stackdriver_key.json"
  redis:
    restart: always
  db:
    restart: always
    volumes:
      - "~/jambuds-db/data:/var/lib/postgresql/data"
    ports:
      - "6002:5432"