const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const createDevMiddleware = require('webpack-dev-middleware');
const MFS = require('memory-fs');

const clientConfig = require('../webpack/client');
const serverConfig = require('../webpack/server');

const readFile = (fs, file) => {
  try {
    return fs.readFileSync(path.join(clientConfig.output.path, file), 'utf-8')
  } catch (e) {}
}

module.exports = function setupDevServer(app, cb) {
  let bundle;
  let clientManifest;

  let readyPromiseResolve;
  const readyPromise = new Promise(r => { readyPromiseResolve = r })

  const update = () => {
    if (bundle && clientManifest) {
      readyPromiseResolve()
      cb(bundle, clientManifest);
    }
  }

  // // read template from disk and watch
  // template = fs.readFileSync(templatePath, 'utf-8')
  // chokidar.watch(templatePath).on('change', () => {
  //   template = fs.readFileSync(templatePath, 'utf-8')
  //   console.log('index.html template updated.')
  //   update()
  // })

  // modify client config to work with hot middleware
  // clientConfig.entry.app = ['webpack-hot-middleware/client', clientConfig.entry.app]
  // clientConfig.output.filename = '[name].js'
  // clientConfig.plugins.push(
  //   new webpack.HotModuleReplacementPlugin(),
  //   new webpack.NoEmitOnErrorsPlugin()
  // )

  // dev middleware
  const clientCompiler = webpack(clientConfig)
  const devMiddleware = createDevMiddleware(clientCompiler, {
    publicPath: clientConfig.output.publicPath,
  })

  app.use(devMiddleware)

  clientCompiler.plugin('done', (webpackStats) => {
    const stats = webpackStats.toJson()
    stats.errors.forEach((err) => console.error(err))
    stats.warnings.forEach((err ) => console.warn(err))

    if (stats.errors.length) {
      return
    }

    clientManifest = JSON.parse(readFile(
      devMiddleware.fileSystem,
      'vue-ssr-client-manifest.json'
    ))

    update()
  })

  // watch and update server renderer
  const serverCompiler = webpack(serverConfig)
  const mfs = new MFS()
  serverCompiler.outputFileSystem = mfs

  serverCompiler.watch({}, (err, webpackStats) => {
    if (err) {
      throw err
    }

    const stats = webpackStats.toJson()
    if (stats.errors.length) {
      return
    }

    // read bundle generated by vue-ssr-webpack-plugin
    bundle = JSON.parse(readFile(mfs, 'vue-ssr-server-bundle.json'))
    update()
  })

  return readyPromise
}