import crypto from 'crypto';

/**
 * Return a randomly-generated bytestring to use as an authentication token. A timestamp is
 * appended to prevent conflicts, as unlikely as they are.
 */
export default function genAuthToken(): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    crypto.randomBytes(24, (err, buf) => {
      if (err) {
        reject(err);
        return;
      }

      const str = buf.toString('hex') + Date.now();
      resolve(str);
    });
  });
}
