name: Run Tests

on: [push]

jobs:
  run-tests:
    name: "Run all tests"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.2-alpine
        env:
          POSTGRES_DB: jambuds_test
        ports:
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:5.0.3-alpine
        ports:
          - 6379/tcp
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Restore/cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Rhiannon
        run: ./gradlew assemble
        working-directory: ./rhiannon

      - name: "-- UNIT TESTS --"
        run: exit 0

      - name: Run Rhiannon unit tests
        run: ./gradlew test
        working-directory: ./rhiannon
        env:
          REDIS_URL: "redis://localhost:${{ job.services.redis.ports[6379] }}"
          JDBC_DATABASE_URL: "jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/jambuds_test?user=postgres&password=postgres"

      - name: "-- INTEGRATION TESTS --"
        run: exit 0
  
      - name: Install app dependencies
        run: npm ci
        working-directory: ./app

      - name: Install psql@11
        run: |
          sudo apt-get install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update
          sudo apt install postgresql-client-11

      - run: npm install -g wait-on

      - name: Build app
        run: npm run build
        working-directory: ./app
        env:
          NODE_ENV: test
          CI: "1"

      - name: Start App server
        run: npm start & wait-on -t 20000 http://localhost:8081
        working-directory: ./app
        env:
          NODE_ENV: test
          CI: "1"
      
      - name: Start Rhiannon server
        run: ./gradlew run & wait-on -t 20000 tcp:7000
        working-directory: ./rhiannon
        env:
          JDBC_DATABASE_URL: "jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/jambuds_test?user=postgres&password=postgres"
          REDIS_URL: "redis://localhost:${{ job.services.redis.ports[6379] }}"
          JAMBUDS_ENV: "feature"
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Install spec dependencies
        run: npm ci
        working-directory: ./spec

      - name: Run Cypress
        run: npm test
        working-directory: ./spec
        env:
          JDBC_DATABASE_URL: "jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/jambuds_test?user=postgres&password=postgres"
          DATABASE_URL: "postgres://postgres@localhost:${{ job.services.postgres.ports[5432] }}/jambuds_test"
          REDIS_URL: "redis://localhost:${{ job.services.redis.ports[6379] }}"